package com.std4453.freemclauncher.net;

public enum Server {
	VERSION_INDEX_SERVER,
	MINECRAFT_DOWNLOAD_SERVER,
	LIBRARIES_SERVER,
	ASSETS_SERVER,
	ASSETS_INDEX_SERVER,
	//old servers
	OLD_ASSETS_INDEX_SERVER,
	OLD_ASSETS_SERVER,
	//TODO:Login servers
}
